name: Build MyMusicMuy Release APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    # 1. AKTIFKAN INI: Mengambil keystore dari Secret KEYSTORE_FILE milikmu
    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app/release.jks

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    # 2. SESUAIKAN NAMA ENV: Disamakan persis dengan nama di GitHub Secrets kamu
    - name: Build Release APK
      env:
        RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact**@v4**
      with:
        name: MyMusicMuy
        path: app/build/outputs/apk/release/app-release.apk

